### ISSUE TITLE
Copying last log line using CTRL+C

### ISSUE THREAD

**Issue by Kabcorp** [JBustos22/oDFe#54]
For non-external console users, it could be really interesting to copy the last printed line of notifications or console using CTRL+C.
Actually, we use \condump

**Comment by Jelvan1** [comment]
What would be the use case for this? I don't think this is practical without the possibility of selecting a line or range. By the time you've decided that you want to copy the last line someone else already pushed a new message into the console.

I do see the usefulness in being able to copy the last URL. But I'd request that feature at Quake3e since that is not a defrag-related issue.

**Comment by Kabcorp** [comment]
Ok I'll put this request in q3e with a better approach and examples.
